// <auto-generated />
using System;
using GoneSoon.Infrastructure.GoneSoon.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GoneSoon.Migrations
{
    [DbContext(typeof(GoneSoonDbContext))]
    partial class GoneSoonDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GoneSoon.Models.NotificationMethodBase", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<Guid>("NoteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("NotificationType")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("NotificationMethods");

                    b.HasDiscriminator<int>("NotificationType");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("GoneSoon.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("GoneSoon.Models.EmailNotificationMethod", b =>
                {
                    b.HasBaseType("GoneSoon.Models.NotificationMethodBase");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("GoneSoon.Models.PushNotificationMethod", b =>
                {
                    b.HasBaseType("GoneSoon.Models.NotificationMethodBase");

                    b.HasDiscriminator().HasValue(3);
                });

            modelBuilder.Entity("GoneSoon.Models.SmsNotificationMethod", b =>
                {
                    b.HasBaseType("GoneSoon.Models.NotificationMethodBase");

                    b.HasDiscriminator().HasValue(2);
                });
#pragma warning restore 612, 618
        }
    }
}
