version: '3.8'

services:
  gone-soon-api:
    image: gone-soon-api
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
      - sqlserver
    environment:
      - ConnectionStrings__Redis=redis:6379
      - ConnectionStrings__SqlServer=Server=sqlserver,1433;Database=GoneSoonDb;User Id=sa;Password=1qaSW2wsDE3edFR!;TrustServerCertificate=True;
    ports:
      - "5000:5000"
      - "5001:5001"
    restart: unless-stopped

  redis:
    image: redis:latest
    restart: always
    command: ["redis-server", "--notify-keyspace-events", "Ex"]
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  redis-commander:
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=1qaSW2wsDE3edFR!
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql

volumes:
  redis_data:
  sqlserver_data: